name: Monitor Merges

on:
  push:
    branches:
      - main  # or any branch you want to monitor

jobs:
  monitor-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Merge Monitor
        uses: YGNT7777/Merge-Monitor@v1.0.0
